# Welcome to Jekyll!
#

# Site settings
title: Pulse
description: |
  The most beautiful Metronome

owner: youxinyu # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: yxydiscovery@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://azureyu.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/yxydiscovery
  github: https://github.com/yogayu
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  weibo: https://weibo.com/yxydiscovery
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
